import { useEffect, useState } from "react";
import { useTranslation } from "react-i18next";
import { useOutletContext } from "react-router-dom";

import { useContentDNA } from "../../features/insights/hooks/useContentDNA.ts";
import { useAnalyticsInsights } from "../../features/insights/hooks/useAnalyticsInsights.ts";
import { useIdentityAI } from "../../features/insights/hooks/useIdentityAI.ts";
import { useCreativeInsights } from "../../features/insights/hooks/useCreativeInsights.ts";
import { useCreativeReport } from "../../features/insights/hooks/useCreativeReport";
import { downloadReport } from "../../utils/downloadReport";
import { useSubscription } from "../../features/subscription/hooks/useSubscription.ts";
import UpgradePrompt from "../../components/ui/UpgradePrompt.tsx";

import { type AnalyticsInsight } from "../../features/insights/types/insights.types.ts";

import "./Identity.scss";

/* =========================
   TYPES
========================= */

type OutletContext = {
  setTopbarContext: (value: string | null) => void;
};

type InsightExpanderProps = {
  code: string;
  insights: AnalyticsInsight[];
  expanded: Record<string, boolean>;
  onToggle: (code: string) => void;
};

/* =========================
   SUBCOMPONENTS
========================= */

function InsightExpander({
  code,
  insights,
  expanded,
  onToggle,
}: InsightExpanderProps) {
  const { t } = useTranslation();
  const insight = insights.find((i) => i.code === code) ?? null;
  if (!insight) return null;

  return (
    <div className="identity-insight-expander">
      <button
        className="identity-insight-toggle"
        onClick={() => onToggle(code)}
      >
        {expanded[code] ? t("identity.hideInsight") : t("identity.seeInsight")}
      </button>

      {expanded[code] && (
        <div className="identity-insight-body">
          <p className="identity-insight-body__insight">
            {t(insight.insight_key, insight.insight_data ?? {})}
          </p>
          <p className="identity-insight-body__strategy">
            {t(insight.strategy_key)}
          </p>
          <p className="identity-insight-body__action">
            {t(insight.action_key)}
          </p>
        </div>
      )}
    </div>
  );
}

function Collapsible({
  icon,
  title,
  subtitle,
  isOpen,
  onToggle,
  children,
}: {
  icon: string;
  title: string;
  subtitle: string;
  isOpen: boolean;
  onToggle: () => void;
  children: React.ReactNode;
}) {
  return (
    <div className="identity-collapsible">
      <div className="identity-collapsible__header" onClick={onToggle}>
        <div className="identity-collapsible__left">
          <span className="identity-collapsible__icon">{icon}</span>
          <div>
            <div className="identity-collapsible__title">{title}</div>
            <div className="identity-collapsible__subtitle">{subtitle}</div>
          </div>
        </div>
        <span
          className={`identity-collapsible__chevron${
            isOpen ? " identity-collapsible__chevron--open" : ""
          }`}
        >
          ▸
        </span>
      </div>
      {isOpen && <div className="identity-collapsible__body">{children}</div>}
    </div>
  );
}

/* =========================
   COMPONENT
========================= */

export default function Identity() {
  const { setTopbarContext } = useOutletContext<OutletContext>();
  const { canUseAI, isFree, trialActive } = useSubscription();

  const { dna, loading: dnaLoading } = useContentDNA();
  const { insights: analyticsInsights } = useAnalyticsInsights("30d");
  const { result: aiResult, loading: aiLoading } = useIdentityAI(dna);
  const { insights: creativeInsights, loading: creativeInsightsLoading } =
    useCreativeInsights();
  const {
    report,
    generatedAt,
    loading: reportLoading,
    generating,
    error: reportError,
    generateReport,
  } = useCreativeReport();

  const { t } = useTranslation();
  const [reportCopied, setReportCopied] = useState(false);
  const [expandedInsights, setExpandedInsights] = useState<
    Record<string, boolean>
  >({});
  const [openSections, setOpenSections] = useState<Record<string, boolean>>({
    reflecting: false,
    deep: false,
  });

  const handleCopyReport = async () => {
    if (!report) return;

    const lines: string[] = [
      `CREATOR IDENTITY REPORT`,
      `━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━`,
      `Generated by Content Intelligence App`,
      ``,
      `━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━`,
      ``,
      `WHO YOU ARE AS A CREATOR`,
      ``,
      report.identity,
      ``,
      `━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━`,
      ``,
      `WHAT'S HAPPENING IN YOUR CONTENT`,
      ``,
      report.current_state,
      ``,
      `━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━`,
      ``,
      `YOUR BIGGEST UNEXPLORED OPPORTUNITY`,
      ``,
      report.opportunity,
      ``,
      `━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━`,
      ``,
      `WORTH SITTING WITH`,
      ``,
      report.question,
      ``,
      `━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━`,
      `AI-assisted creative analysis. AI-generated outputs`,
      `may not be eligible for copyright protection.`,
      `Content Intelligence App does not claim IP rights over this output.`,
    ];

    const text = lines.join("\n");

    try {
      await navigator.clipboard.writeText(text);
      setReportCopied(true);
      setTimeout(() => setReportCopied(false), 2000);
    } catch {
      // silent — clipboard API may not be available
    }
  };

  const toggleInsight = (code: string) => {
    setExpandedInsights((prev) => ({ ...prev, [code]: !prev[code] }));
  };

  const toggleSection = (key: string) => {
    setOpenSections((prev) => ({ ...prev, [key]: !prev[key] }));
  };

  /* =========================
     TOPBAR CONTEXT
  ========================= */

  useEffect(() => {
    setTopbarContext(t("identity.subtitle"));
    return () => setTopbarContext(null);
  }, [setTopbarContext, t]);

  /* =========================
     HELPERS
  ========================= */

  const getInsight = (code: string) =>
    analyticsInsights.find((i) => i.code === code) ?? null;

  /* =========================
     LOADING
  ========================= */

  if (dnaLoading) {
    return (
      <div className="identity-page">
        <p>{t("identity.loadingIdentity")}</p>
      </div>
    );
  }

  /* =========================
     RENDER
  ========================= */

  return (
    <div className="identity-page">

      {/* ── ROW 1 — Top ideas + Top topics ── */}

      <div className="identity-row-two">
        <div className="identity-pattern-card">
          <span className="section-label">{t("identity.topIdeas")}</span>
          <ol className="identity-ideas-list">
            {(dna?.top_ideas ?? []).map((idea, i) => (
              <li key={i} className="identity-ideas-list__item">
                <span className="identity-ideas-list__rank">{i + 1}</span>
                <span className="identity-ideas-list__title">{idea.title}</span>
                <span className="identity-ideas-list__count">
                  {idea.content_count}{" "}
                  {idea.content_count === 1 ? t("ideas.content") : t("ideas.contents")}
                </span>
              </li>
            ))}
          </ol>
        </div>

        <div className="identity-pattern-card">
          <span className="section-label">{t("identity.topTopics")}</span>
          <div className="identity-bars">
            {(dna?.topic_distribution ?? []).map((item) => (
              <div key={item.topic} className="identity-bars__row">
                <span className="identity-bars__label">{item.topic}</span>
                <div className="identity-bars__track">
                  <div
                    className="identity-bars__fill"
                    style={{ width: `${item.percentage}%` }}
                  />
                </div>
                <span className="identity-bars__percentage">
                  {item.percentage}%
                </span>
              </div>
            ))}
          </div>
          <InsightExpander
            code="dominant_topic"
            insights={analyticsInsights}
            expanded={expandedInsights}
            onToggle={toggleInsight}
          />
        </div>
      </div>

      {/* ── ROW 2 — Content roles ancho completo ── */}

      <div className="identity-pattern-card" style={{ marginBottom: "12px" }}>
        <span className="section-label">{t("identity.contentRoles")}</span>
        <div className="identity-roles-row">
          {(dna?.role_distribution ?? []).map((item) => (
            <div key={item.role} className="identity-stat-card">
              <span className="identity-stat-card__value">
                {item.percentage}%
              </span>
              <span className="identity-stat-card__label">{t(`contentRoles.${item.role}`, { defaultValue: item.role })}</span>
            </div>
          ))}
        </div>
        <InsightExpander
          code="content_role"
          insights={analyticsInsights}
          expanded={expandedInsights}
          onToggle={toggleInsight}
        />
      </div>

      {/* ── ROW 3 — Platforms + Formats ── */}

      <div className="identity-row-two">
        <div className="identity-pattern-card">
          <span className="section-label">{t("identity.platforms")}</span>
          <div className="identity-bars">
            {(dna?.platform_distribution ?? []).map((item) => (
              <div key={item.platform} className="identity-bars__row">
                <span className="identity-bars__label">{item.platform}</span>
                <div className="identity-bars__track">
                  <div
                    className="identity-bars__fill"
                    style={{ width: `${item.percentage}%` }}
                  />
                </div>
                <span className="identity-bars__percentage">
                  {item.percentage}%
                </span>
              </div>
            ))}
          </div>
          <InsightExpander
            code="top_platform"
            insights={analyticsInsights}
            expanded={expandedInsights}
            onToggle={toggleInsight}
          />
        </div>

        <div className="identity-pattern-card">
          <span className="section-label">{t("identity.formats")}</span>
          <div className="identity-bars">
            {(dna?.format_distribution ?? []).map((item) => (
              <div key={item.format} className="identity-bars__row">
                <span className="identity-bars__label">{item.format}</span>
                <div className="identity-bars__track">
                  <div
                    className="identity-bars__fill"
                    style={{ width: `${item.percentage}%` }}
                  />
                </div>
                <span className="identity-bars__percentage">
                  {item.percentage}%
                </span>
              </div>
            ))}
          </div>
          <InsightExpander
            code="best_format"
            insights={analyticsInsights}
            expanded={expandedInsights}
            onToggle={toggleInsight}
          />
        </div>
      </div>

      {/* ── STANDOUT INSIGHTS — gated por plan ── */}

      <section className="identity-section">
        <span className="section-label">
          {t("identity.standoutInsights")}
        </span>
        {canUseAI ? (
          (aiLoading || (aiResult?.standout_insights?.length ?? 0) > 0) && (
            <div className="identity-highlights">
              {aiLoading ? (
                <>
                  <div className="identity-highlight-card identity-highlight-card--skeleton" />
                  <div className="identity-highlight-card identity-highlight-card--skeleton" />
                </>
              ) : (
                <>
                  {aiResult?.standout_insights.slice(0, 2).map((insight, i) => (
                    <div key={i} className="identity-highlight-card">
                      <span className="identity-highlight-card__title">
                        {insight.title}
                      </span>
                      <p>{insight.text}</p>
                    </div>
                  ))}
                  {getInsight("content_production") && (
                    <div className="identity-highlight-card">
                      <p>
                        {t(
                          getInsight("content_production")!.insight_key,
                          getInsight("content_production")!.insight_data ?? {},
                        )}{" "}
                        {t(getInsight("content_production")!.strategy_key)}
                      </p>
                    </div>
                  )}
                </>
              )}
            </div>
          )
        ) : (
          isFree && !trialActive && (
            <UpgradePrompt
              title={t("upgrade.insightsTitle")}
              description={t("upgrade.insightsDesc")}
            />
          )
        )}
      </section>

      {/* ── CREATIVE STYLE — gated por plan ── */}

      <section className="identity-section">
        <span className="section-label">{t("identity.creativeStyle")}</span>
        {canUseAI ? (
          (aiLoading || (aiResult?.creative_style_tags?.length ?? 0) > 0) && (
            <div className="identity-tags">
              {aiLoading ? (
                <>
                  {[80, 110, 95, 130, 75].map((w, i) => (
                    <span
                      key={i}
                      className="identity-tag identity-tag--skeleton"
                      style={{ width: w }}
                    />
                  ))}
                </>
              ) : (
                aiResult?.creative_style_tags.map((item, i) => (
                  <span
                    key={i}
                    className={`identity-tag ${item.active ? "identity-tag--active" : ""}`}
                  >
                    {item.tag}
                  </span>
                ))
              )}
            </div>
          )
        ) : (
          isFree && !trialActive && (
            <div className="identity-tags identity-tags--locked" aria-hidden="true">
              {["···", "·····", "····", "······", "···"].map((dots, i) => (
                <span key={i} className="identity-tag identity-tag--locked">{dots}</span>
              ))}
            </div>
          )
        )}
      </section>

      {/* ── WORTH REFLECTING ON — colapsable ── */}

      <Collapsible
        icon="🔍"
        title={t("identity.worthReflecting")}
        subtitle={t("identity.worthReflectingSubtitle")}
        isOpen={openSections.reflecting}
        onToggle={() => toggleSection("reflecting")}
      >
        {!canUseAI && isFree && !trialActive ? (
          <UpgradePrompt
            title={t("upgrade.insightsTitle")}
            description={t("upgrade.insightsDesc")}
            compact
          />
        ) : creativeInsightsLoading ? (
          <>
            <div className="identity-insight-card identity-insight-card--skeleton" />
            <div className="identity-insight-card identity-insight-card--skeleton" />
          </>
        ) : creativeInsights.length === 0 ? (
          <p style={{ fontSize: "13px", color: "#6b7280", margin: 0 }}>
            {t("identity.notEnoughData")}
          </p>
        ) : (
          creativeInsights.map((insight, i) => (
            <div key={i} className="identity-insight-card">
              <span className="identity-insight-card__label">
                {insight.label}
              </span>
              <p className="identity-insight-card__text">{insight.text}</p>
            </div>
          ))
        )}
      </Collapsible>

      {/* ── DEEP ANALYSIS — colapsable ── */}

      <Collapsible
        icon="✦"
        title={t("identity.deepAnalysis")}
        subtitle={
          report
            ? `${t("identity.deepAnalysisLastGenerated")} ${new Date(generatedAt!).toLocaleDateString()}`
            : t("identity.deepAnalysisSubtitle")
        }
        isOpen={openSections.deep}
        onToggle={() => toggleSection("deep")}
      >
        {!canUseAI && isFree && !trialActive ? (
          <UpgradePrompt
            title={t("upgrade.reportTitle")}
            description={t("upgrade.reportDesc")}
          />
        ) : reportLoading ? (
          <div className="identity-report-loading">
            <p>{t("common.loading")}</p>
          </div>
        ) : report ? (
          <div className="identity-report">
            <div className="identity-report__section">
              <span className="identity-report__label">
                {t("identity.whoYouAre")}
              </span>
              <p className="identity-report__text">{report.identity}</p>
            </div>

            <div className="identity-report__section">
              <span className="identity-report__label">
                {t("identity.whatsHappening")}
              </span>
              <p className="identity-report__text">{report.current_state}</p>
            </div>

            <div className="identity-report__section">
              <span className="identity-report__label">
                {t("identity.biggestOpportunity")}
              </span>
              <p className="identity-report__text">{report.opportunity}</p>
            </div>

            <div className="identity-report__section identity-report__section--question">
              <span className="identity-report__label">
                {t("identity.worthSittingWith")}
              </span>
              <p className="identity-report__question">{report.question}</p>
            </div>

            <p className="identity-report__disclaimer">
              {t("identity.disclaimer")}
            </p>

            <div className="identity-report__footer">
              <span className="identity-report__date">
                {t("identity.generatedOn")} {new Date(generatedAt!).toLocaleDateString()}
              </span>
              <div style={{ display: "flex", gap: "8px" }}>
                <button
                  className="identity-report__copy"
                  onClick={handleCopyReport}
                  type="button"
                >
                  {reportCopied
                    ? t("identity.copied")
                    : t("identity.copyReport")}
                </button>
                <button
                  className="identity-report__download"
                  onClick={() =>
                    report && generatedAt && downloadReport(report, generatedAt)
                  }
                  type="button"
                >
                  {t("identity.downloadReport")}
                </button>
                <button
                  className="identity-report__regenerate"
                  onClick={() => generateReport(dna, true)}
                  disabled={generating}
                  type="button"
                >
                  {generating
                    ? t("identity.regenerating")
                    : t("identity.regenerate")}
                </button>
              </div>
            </div>

            {reportError && (
              <p className="identity-report__error">{reportError}</p>
            )}
          </div>
        ) : (
          <div className="identity-report-placeholder">
            <p className="identity-report-placeholder__title">
              {t("identity.reportTitle")}
            </p>
            <p className="identity-report-placeholder__sub">
              {t("identity.reportSubtitle")}
            </p>
            {reportError && (
              <p className="identity-report__error">{reportError}</p>
            )}
            <button
              className="btn-primary"
              onClick={() => generateReport(dna)}
              disabled={generating}
              type="button"
            >
              {generating
                ? t("identity.generatingReport")
                : t("identity.generateReport")}
            </button>
            {generating && (
              <p className="identity-report-placeholder__hint">
                {t("identity.generatingHint")}
              </p>
            )}
          </div>
        )}
      </Collapsible>
    </div>
  );
}
